In [76]:
from __future__ import print_function
import numpy as np
from sklearn import neighbors
from sklearn.model_selection import train_test_split # for splitting data
from sklearn import metrics

import pandas as pd

## read data from csv

In [77]:
linearDF = pd.read_csv('./linear.csv')

In [78]:
linearDF.head()

x          y
0  77  79.775152
1  21  23.177279
2  22  25.609262
3  20  17.857388
4  36  41.849864

In [79]:
# Lấy giá trị y ra 1 mảng từ dataframe
yArray = linearDF["y"].to_numpy()
yArray[:10]

array([79.77515201, 23.17727887, 25.60926156, 17.85738813, 41.84986439,
        9.80523488, 58.87465933, 97.61793701, 18.39512747,  8.74674765])

In [80]:
# tương tự với mảng x
xArray = linearDF["x"].to_numpy()
xArray[:10]

array([77, 21, 22, 20, 36, 15, 62, 95, 20,  5], dtype=int64)

In [83]:
# Chia tập dữ liệu thành 2 tập train và test
X_train, X_test, y_train, y_test = train_test_split(xArray, yArray, random_state=10)

In [112]:
# Xây dựng mô hình dự báo KNN với k = 7 và độ đo l2 nomp
model = neighbors.KNeighborsRegressor(n_neighbors=7, p = 2, weights='distance')
model.fit(X_train.reshape(-1,1), y_train)

# dự báo giá trị y của tập test
y_pred = model.predict(X_test.reshape(-1,1))
y_pred

array([ 97.1082562 ,  16.27930025,  97.1082562 , 104.4884975 ,
        23.91657301,  97.1082562 ,  51.57326718, 104.4884975 ,
        -2.7611826 ,  21.49879735,  45.96396877,  77.55021421,
        91.30823453,  58.51434364,   8.74674765,  77.91032969,
        31.68294168,  21.49879735,  48.8338439 ,  21.32273728,
        52.01932286,  53.19294125,  62.71453064,  84.92113014,
        49.49983031,  48.8338439 ,  62.71453064,  74.30343542,
        38.07419821,  10.35357191,  67.28725332,  35.74983309,
        55.45944569,  91.30823453,  71.44337591,  60.13133298,
        95.63444826,  73.38109802,   8.74674765,  78.79008525,
        28.71342683,  69.45498498,  53.19294125,  -2.81991397,
        73.38109802,  51.57326718,  50.17008622,  -2.7611826 ,
        50.17008622,   6.99732472,  71.44337591,  18.99681823,
        18.99681823,  -1.69242638,  16.0452578 ,  97.79086532,
        18.99681823,  67.28725332,  57.0773846 ,  36.0760852 ,
        49.57480328,  73.2300846 ,  62.71453064,  71.60

In [113]:
y_test

array([ 97.41206981,  17.76197116,  97.70342201,  99.78687252,
        30.49412933, 101.0697879 ,  56.14834113, 105.5918375 ,
         5.3136862 ,  25.69041546,  37.08457698,  78.04237454,
        91.36566374,  60.91792707,   0.67607675,  78.31056542,
        24.18437976,  23.52647153,  48.35172635,  30.41303282,
        54.08170635,  51.80035866,  67.38654703,  85.45504157,
        52.28620611,  46.56141773,  64.37521087,  75.07484683,
        40.00709598,  12.07991648,  65.01324035,  29.38505024,
        57.01631363,  91.69240746,  69.39858505,  63.29717058,
        94.79081712,  70.34969772,   5.6340309 ,  73.9308764 ,
        26.49487961,  67.22008001,  55.81628509,  -1.63296825,
        72.86282528,  53.11628433,  60.20758349,   0.27530726,
        53.62235225,   2.81141583,  77.9969477 ,  16.68715211,
        16.74923937,  -3.46788379,  21.42637785,  99.87382707,
        11.21710477,  70.3698748 ,  53.32005764,  47.49374765,
        51.69967172,  74.25362837,  67.68142149,  77.22

In [116]:
# Độ chính xác bằng: 97.98%

print("accuracy:", model.score(X_test.reshape(-1,1), y_test))
print("R2:", metrics.r2_score(y_test, y_pred.reshape(-1,1)))
# print("F1_score:", metrics.f1_score(y_test, y_pred))

accuracy: 0.9798072111270179
R2: 0.9798072111270179
